version: '1.0'
name: pipeline-20240515
displayName: pipeline-20240515
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-85983b3f
    displayName: 下载 Go 环境
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.22'
        commands:
          - '# 默认使用goproxy.cn'
          - export GOPROXY=https://goproxy.cn
          - '# 输入你的构建命令'
          - make build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./output
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
