version: '1.0'
name: pipeline-20240515
displayName: pipeline-20240515
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-85983b3f
    displayName: 下载 Go 环境
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.22'
        commands:
          - '# 默认使用goproxy.cn'
          - export GOPROXY=https://goproxy.cn
          - '# 输入你的构建命令'
          - make build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./output
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
  - name: stage-6d967161
    displayName: test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@golang
        name: unit_test_go
        displayName: Golang 单元测试
        golangVersion: '1.22'
        commands:
          - '# 默认使用goproxy.cn用户可手动调整'
          - export GOPROXY=https://goproxy.cn
          - '# 默认的单元测试命令'
          - '# 输出测试报告目录到当前工作目录，可自动上传并展示'
          - mkdir -p golang-report
          - '# 未使用Go Mod的用户需要打开一下注释'
          - '# export GOFLAGS=-mod=vendor'
          - go test -v -json -cover -coverprofile cover.out ./... > golang-report/report.jsonl
          - go tool cover -html=cover.out -o golang-report/index.html
        report:
          path: golang-report
          file: report.jsonl
          index: index.html
        checkpoints: []
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
